POST https://deploy.sinistercode.com/soothsayer
Content-Type: application/json
Accept: application/json
User-Agent: deploy-test

{
  "zen": "Avoid administrative distraction.",
  "hook_id": 402052848,
  "hook": {
    "type": "Repository",
    "id": 402052848,
    "name": "web",
    "active": true,
    "events": [
      "push"
    ],
    "config": {
      "content_type": "json",
      "insecure_ssl": "0",
      "secret": "sinistercode-deploy-3202",
      "url": "https://deploy.sinistercode.com/soothsayer"
    },
    "updated_at": "2023-02-21T19:58:06Z",
    "created_at": "2023-02-21T19:58:06Z",
    "url": "https://api.github.com/repos/macnod/soothsayer/hooks/402052848",
    "test_url": "https://api.github.com/repos/macnod/soothsayer/hooks/402052848/test",
    "ping_url": "https://api.github.com/repos/macnod/soothsayer/hooks/402052848/pings",
    "deliveries_url": "https://api.github.com/repos/macnod/soothsayer/hooks/402052848/deliveries",
    "last_response": {
      "code": null,
      "status": "unused",
      "message": null
    }
  },
  "repository": {
    "id": 598311248,
    "node_id": "R_kgDOI6mBUA",
    "name": "soothsayer",
    "full_name": "macnod/soothsayer",
    "private": true,
    "owner": {
      "login": "macnod",
      "id": 84950,
      "node_id": "MDQ6VXNlcjg0OTUw",
      "avatar_url": "https://avatars.githubusercontent.com/u/84950?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/macnod",
      "html_url": "https://github.com/macnod",
      "followers_url": "https://api.github.com/users/macnod/followers",
      "following_url": "https://api.github.com/users/macnod/following{/other_user}",
      "gists_url": "https://api.github.com/users/macnod/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/macnod/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/macnod/subscriptions",
      "organizations_url": "https://api.github.com/users/macnod/orgs",
      "repos_url": "https://api.github.com/users/macnod/repos",
      "events_url": "https://api.github.com/users/macnod/events{/privacy}",
      "received_events_url": "https://api.github.com/users/macnod/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/macnod/soothsayer",
    "description": "A simple web app that uses the OpenAI API",
    "fork": false,
    "url": "https://api.github.com/repos/macnod/soothsayer",
    "forks_url": "https://api.github.com/repos/macnod/soothsayer/forks",
    "keys_url": "https://api.github.com/repos/macnod/soothsayer/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/macnod/soothsayer/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/macnod/soothsayer/teams",
    "hooks_url": "https://api.github.com/repos/macnod/soothsayer/hooks",
    "issue_events_url": "https://api.github.com/repos/macnod/soothsayer/issues/events{/number}",
    "events_url": "https://api.github.com/repos/macnod/soothsayer/events",
    "assignees_url": "https://api.github.com/repos/macnod/soothsayer/assignees{/user}",
    "branches_url": "https://api.github.com/repos/macnod/soothsayer/branches{/branch}",
    "tags_url": "https://api.github.com/repos/macnod/soothsayer/tags",
    "blobs_url": "https://api.github.com/repos/macnod/soothsayer/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/macnod/soothsayer/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/macnod/soothsayer/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/macnod/soothsayer/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/macnod/soothsayer/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/macnod/soothsayer/languages",
    "stargazers_url": "https://api.github.com/repos/macnod/soothsayer/stargazers",
    "contributors_url": "https://api.github.com/repos/macnod/soothsayer/contributors",
    "subscribers_url": "https://api.github.com/repos/macnod/soothsayer/subscribers",
    "subscription_url": "https://api.github.com/repos/macnod/soothsayer/subscription",
    "commits_url": "https://api.github.com/repos/macnod/soothsayer/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/macnod/soothsayer/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/macnod/soothsayer/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/macnod/soothsayer/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/macnod/soothsayer/contents/{+path}",
    "compare_url": "https://api.github.com/repos/macnod/soothsayer/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/macnod/soothsayer/merges",
    "archive_url": "https://api.github.com/repos/macnod/soothsayer/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/macnod/soothsayer/downloads",
    "issues_url": "https://api.github.com/repos/macnod/soothsayer/issues{/number}",
    "pulls_url": "https://api.github.com/repos/macnod/soothsayer/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/macnod/soothsayer/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/macnod/soothsayer/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/macnod/soothsayer/labels{/name}",
    "releases_url": "https://api.github.com/repos/macnod/soothsayer/releases{/id}",
    "deployments_url": "https://api.github.com/repos/macnod/soothsayer/deployments",
    "created_at": "2023-02-06T20:59:51Z",
    "updated_at": "2023-02-06T21:23:56Z",
    "pushed_at": "2023-02-14T18:18:02Z",
    "git_url": "git://github.com/macnod/soothsayer.git",
    "ssh_url": "git@github.com:macnod/soothsayer.git",
    "clone_url": "https://github.com/macnod/soothsayer.git",
    "svn_url": "https://github.com/macnod/soothsayer",
    "homepage": null,
    "size": 22,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Python",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc6TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [],
    "visibility": "private",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  "sender": {
    "login": "macnod",
    "id": 84950,
    "node_id": "MDQ6VXNlcjg0OTUw",
    "avatar_url": "https://avatars.githubusercontent.com/u/84950?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/macnod",
    "html_url": "https://github.com/macnod",
    "followers_url": "https://api.github.com/users/macnod/followers",
    "following_url": "https://api.github.com/users/macnod/following{/other_user}",
    "gists_url": "https://api.github.com/users/macnod/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/macnod/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/macnod/subscriptions",
    "organizations_url": "https://api.github.com/users/macnod/orgs",
    "repos_url": "https://api.github.com/users/macnod/repos",
    "events_url": "https://api.github.com/users/macnod/events{/privacy}",
    "received_events_url": "https://api.github.com/users/macnod/received_events",
    "type": "User",
    "site_admin": false
  }
}